FROM codercom/ubuntu-dev
ENV VERSION "go1.12"
RUN curl https://storage.googleapis.com/golang/$VERSION.linux-amd64.tar.gz | sudo tar -C /usr/local -xzf -
RUN sudo ln -s /usr/local/go/bin/go /usr/local/bin/go
